language: node_js
node_js:
  - "12"
sudo: required
dist: bionic
addons:
  firefox: "latest"
  chrome: stable
before_install:
  - firefox --version 2>/dev/null
  - google-chrome --product-version
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1600x1024x16
script:
  - npm run travis
  - node ./bin/webcoach.js -b chrome https://www.sitespeed.io > output.json
  - node ./bin/webcoach.js -b firefox https://www.sitespeed.io > output.json
  - node ./bin/webcoach.js -b chrome --mobile https://www.sitespeed.io > output.json
notifications:
  slack:
    secure: O0JhuiCt4htoIok2wybQTVooxU64cBG3kh8rctve5pvQb2XPkOCVRmbEYAbtEm5lOM2Ri0f8n2f+n3qegMj/GE1lDv0uvgdL/8PYzq4RMl5HHlfVFkB49LHNDMHLwdHts6yI55W+FNTo6+ud+oJgXDEBdrjjsS2A+keiLy5Ai6cYMN9jNyWOQladIjcTAJFCbESuTznyjn3ljg+eG2ZdAHyVBXiX4uvWvd3lVgfjCf/Izhoyi0y8ZWfGZ7TdKhRyOAD+VqRQZlyc0CxI3mhJVZWkRAzHD/yWcSUvl60udi9xt1t1Ce79S0kBKcpZ5LoZ+UcfIzD9e4Fh1gran8a7qRgpuHtfG2wuAirIztxSWYq1Z1TJdFMsGqUhA1Z+D7ZXr4uwnEV+WX6H3nW/0dMP0gZI1vknzdW+CBUWXsicJLsV+MqWbnHlxNlTvoqJow0mUmIqh91lAIR21Wbx+xpccEFPo5iwFhh5yoI9S9j7mqVEIXv04nDw2tPEKFYPFnMdvOjqPXf1nEnHQdh4Pwi9RnNZuW2XWtZR0OW6zwxiAgbrQIa5K1tzVERClXLdUmz8zgktG+IkZseexEXUJjrKfNaOLrg4wwWwj5oCuZHXLlFOg0b8he73OCCXjJfzi8kBXqQDGuN3t4lT1RMLV4nCmQ1s6UjapiJ5lj/FlAoVZWM=
